---
# This playbook will install MariaDB and create db user and give permissions.
  - name: Install MariaDB package
    yum: 
      name: 
        - mariadb-server 
        - python3-PyMySQL
      state: present

  - name: Configure SELinux to start mysql on any port
    seboolean: name=mysql_connect_any state=true persistent=yes

  - name: Create Mysql configuration file
    template: src=/home/ansible/ansible/obligatorio_2021_08/lamp/roles/db/templates/my.cnf.j2 dest=/var/lib/mysql
    notify:
    - restart mariadb

  - name: Create MariaDB log file
    file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

  - name: Create MariaDB PID directory
    file: path=/var/run/mysqld state=touch owner=mysql group=mysql mode=0775

  - name: Start MariaDB Service
    service: name=mariadb state=started enabled=yes

  - name: Start firewalld
    service: name=firewalld state=started enabled=yes

  - name: insert firewalld rule
    firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes

  - name: Create Application Database
    mysql_db: 
      name={{ dbname }} 
      state=present 
   #   config_file=/home/ansible/ansible/obligatorio_2021_08/lamp/roles/db/templates/my.cnf.j2

  - name: Create Application DB User
    mysql_user: 
      check_implicit_admin=true
      name={{ dbname }} 
      login_user={{ dbuser }}
      login_password={{ upassword }} 
      password={{ upassword }}
      priv=*.*:ALL 
      host='%' 
      state=present
      update_password=always 
      #config_file=/home/ansible/ansible/obligatorio_2021_08/lamp/roles/db/templates/my.cnf.j2

