---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

#- hosts: all

- name: Copy the code from repository
  git: repo=https://github.com/mauropillox/obligatorio_2021_08.git dest=/var/www/html/
  when: ansible_facts['os_family'] == "Ubuntu"

- name: Creates the index.php file
  template: src=index.php.j2 dest=/var/www/html/index.php
  when: ansible_facts['os_family'] == "Ubuntu"
